### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by fpg1503** [CaliAlec/Forever-Thankful-On-FB#1]
The extension stopped working, I think Facebook disabled the Thankful Reactions forever 😞

**Comment by corgigod** [comment]
It seems like the emote is still available on Facebook's servers, as it shows up for a fraction of a second before it says the content is un-available.

**Comment by sammarcus** [comment]
There are several additional reactions that appear, but just because it's visible on their server doesn't mean it will let you actually submit it unfortunately 😞  Shortly after this was published Facebook started rejecting sent Thankful reactions on their end. You can see this in the dev console when you try to send one.

**Comment by CaliAlec** [comment]
I believe that it's visible for a split second because it submits the reaction on the client, but when the server responds by rejecting it, it reverts back. I still see Thankful Reactions on some posts though, so somehow people are still able to submit them. It appears that certain countries are still allowed to post Thankful reacts, but I'm not sure which ones. I doubt it's possible to trick the server into thinking you're from one of those whitelisted countries in the request because the server probably validates what country you are really from ¯\_(ツ)_/¯

**Comment by Convult** [comment]
@CaliAlec do you know any of the whitelisted countries?

**Comment by sammarcus** [comment]
For the posts you're seeing it on, were they created after this was fixed? I see them on older posts too, but they just have retained it from when it was still allowed. If the reaction is switched to a different one, it wouldn't even be able to be switched back to Thankful state anymore, either.

**Comment by CaliAlec** [comment]
@sammarcus Yeah, people were sending Thankful Reactions after this was fixed because they were coming from people in countries still whitelisted by Facebook. I haven't seen any on recent posts, so I believe no one is allowed to use it anymore. All the old ones will continue to exist.
